name = "dom"
version = "0.1.0"

[ source ]
owner = "stefan-hoeck"
repo = "idris2-dom"
rev = "v0.1.0"
sha256 = "sha256-bHy+bcq92WeNdHlfzrZyu6PfX0Zd9y2qURFk0G+OXS0="

[ depends ]
idrisLibs = [ "sop" "experimental" ]