name = "experimental"
version = "0.2.0"

[ source ]
owner = "stefan-hoeck"
repo = "idris2-experimental"
rev = "2e4b2699bd1baa18a4a11883ff9e2d5fb6dafad8"
sha256 = "sha256-52OeqhXsEwWezTj8lDgS6xiNsuEeJQUhzGLSp86+6Js="
